services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - devnet

  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devnet
  postgres:
    image: postgres:15
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    environment:
      PMA_HOSTS: mariadb,mysql,host.docker.internal
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mariadb
      - mysql
    networks:
      - devnet
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8072:80"
    depends_on:
      - postgres
    networks:
      - devnet

  adminer:
    image: adminer
    container_name: my_adminer
    restart: always
    ports:
      - "8083:8080"
    networks:
      - devnet

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "8025:8025"
    networks:
      - devnet
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  php_fpm:
    image: php:8.2-fpm
    container_name: php_fpm
    restart: always
    volumes:
      - ./www:/var/www/html
    networks:
      - devnet
  meilisearch:
    image: getmeili/meilisearch
    container_name: meili
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: true
    networks:
      - devnet
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    networks:
      - devnet

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm
    networks:
      - devnet
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9024:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - devnet

volumes:
  mariadb_data:
  mysql_data:
  pgdata:
  portainer_data:

networks:
  devnet:
